### PR TITLE
Fix thread leak in legacy query path

### LINKED ISSUE #880: Legacy query path leads to thread leaks in case of state machine exceptions
The following code path leads to an unreleased thread in the case of the worker / state machine exceptions (or RejectedExecutionException):

```
io.temporal.internal.worker.WorkflowExecutionException: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@4176e14b[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@4beb70[Wrapped task = io.temporal.internal.sync.WorkflowThreadImpl$RunnableWrapper@4747fa1]] rejected from java.util.concurrent.ThreadPoolExecutor@1faac87d[Running, pool size = 600, active threads = 600, queued tasks = 0, completed tasks = 14007]
at io.temporal.internal.sync.POJOWorkflowImplementationFactory.mapToWorkflowExecutionException(POJOWorkflowImplementationFactory.java:359)
at io.temporal.internal.sync.SyncWorkflow.mapUnexpectedException(SyncWorkflow.java:192)
at io.temporal.internal.replay.ReplayWorkflowExecutor.mapUnexpectedException(ReplayWorkflowExecutor.java:152)
at io.temporal.internal.replay.ReplayWorkflowRunTaskHandler.handleWorkflowTaskImpl(ReplayWorkflowRunTaskHandler.java:191)
at io.temporal.internal.replay.ReplayWorkflowRunTaskHandler.handleQueryWorkflowTask(ReplayWorkflowRunTaskHandler.java:246)
at io.temporal.internal.replay.ReplayWorkflowTaskHandler.handleQueryOnlyWorkflowTask(ReplayWorkflowTaskHandler.java:267)
at io.temporal.internal.replay.ReplayWorkflowTaskHandler.handleWorkflowTask(ReplayWorkflowTaskHandler.java:107)
at io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.handle(WorkflowWorker.java:314)
at io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.handle(WorkflowWorker.java:274)
at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:73)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
```

### PR DESCRIPTION
**Pull request by Spikhalskiy**
Fix thread leak in legacy query path
Refactor replay functionality into a separate class to keep clear from the main code path and worker code

Closes #880

### CODE REVIEW

File: temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java [hunk 1]
```diff
@@ -101,20 +101,119 @@ public ReplayWorkflowTaskHandler(
...
+          getOrCreateWorkflowExecutor(useCache, workflowTask, metricsScope, createdNew);
+      WorkflowTaskResult result = workflowRunTaskHandler.handleWorkflowTask(workflowTask);
+      if (result.isFinalCommand()) {
+        cache.invalidate(execution, metricsScope, "FinalCommand", null);
+      } else if (useCache && createdNew.get()) {
+        cache.addToCache(execution, workflowRunTaskHandler);
+      }
+      return createCompletedWFTRequest(
+          workflowTask.getWorkflowType().getName(), workflowTask, result);
     } catch (Throwable e) {
```
Comment (cretz) [inline temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java:139]: Can any of the things in here throw themselves?

File: temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java [hunk 2]
```diff
@@ -101,20 +101,119 @@ public ReplayWorkflowTaskHandler(
...
+        // yet and we can avoid doing a reset.
+        if (!isFullHistory(workflowTask)) {
+          resetStickyTaskQueue(execution);
+        }
+      }
+      throw e;
+    } finally {
+      if (useCache) {
+        cache.markProcessingDone(execution);
+      } else if (workflowRunTaskHandler != null) {
```
Comment (cretz) [inline temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java:159]: What if I'm using cache _and_ this is not null?

File: temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java [hunk 3]
```diff
@@ -101,20 +101,119 @@ public ReplayWorkflowTaskHandler(
...
+        workflowRunTaskHandler.close();
```
Comment (cretz) [inline temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java:160]: Is this safe for calling multiple times? You may call this in the catch block and again here.

Comment (Spikhalskiy) [reply temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java:160]: Yeah, it is. I will port a comment here.

File: temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java (hunk 2 above)
Comment (Spikhalskiy) [reply temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java:159]: We don't close, we leave it open in cache, just marked as done.

File: temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java (hunk 1 above)
Comment (Spikhalskiy) [reply temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java:139]: Well, resetStickyTaskQueue actually can, good thinking. I will wrap it into a catch block that ignores it and logs instead.

File: temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java [hunk 4]
```diff
@@ -168,59 +267,32 @@ private Result failureToResult(PollWorkflowTaskQueueResponse workflowTask, Throw
...
-                return createStatefulHandler(workflowTask, metricsScope);
-              });
-    }
-    return workflowRunTaskHandler;
-  }
-
-  private Result handleWorkflowTaskWithEmbeddedQuery(
-      PollWorkflowTaskQueueResponse.Builder workflowTask, Scope metricsScope) throws Throwable {
+  /** LEGACY QUERY IMPLEMENTATION */
+  private Result handleQueryOnlyWorkflowTask(
```
Comment (Sushisource) [inline temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java:271]: Honestly I would change this name. It's really not a real workflow task, given we respond on a totally different API

File: temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java [hunk 5]
```diff
@@ -230,62 +302,36 @@ private Result handleWorkflowTaskWithEmbeddedQuery(
...
-        log.trace(
-            "Closing runner for {}-{} because of non-sticky worker configuration",
-            execution.getWorkflowId(),
-            execution.getRunId());
-        workflowRunTaskHandler.close();
-      } else {
+      if (useCache) {
         cache.markProcessingDone(execution);
+      } else if (workflowRunTaskHandler != null) {
+        workflowRunTaskHandler.close();
```
Comment (Sushisource) [inline temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java:308]: Should this be just `if` rather than `else if`? If we're not using the cache will the handler just be closed because it's disposed of?

File: temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java [hunk 6]
```diff
@@ -230,62 +302,36 @@ private Result handleWorkflowTaskWithEmbeddedQuery(
...
-        cache.addToCache(execution, workflowRunTaskHandler);
-      }
-      if (queryResult.isPresent()) {
-        queryCompletedRequest.setQueryResult(queryResult.get());
-      }
-      queryCompletedRequest.setCompletedType(QueryResultType.QUERY_RESULT_TYPE_ANSWERED);
-    } catch (Throwable e) {
+
+    if (e != null) {
+      queryCompletedRequest.setCompletedType(QueryResultType.QUERY_RESULT_TYPE_FAILED);
```
Comment (Sushisource) [inline temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java:323]: Super nitpicky feel free to ignore: I would invert the conditional here. It's nice to read happy path first.

File: temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowWorker.java [hunk 7]
```diff
@@ -99,6 +96,22 @@ public SyncWorkflowWorker(
     workflowWorker =
         new WorkflowWorker(
             service, namespace, taskQueue, singleWorkerOptions, taskHandler, stickyTaskQueueName);
+
+    // it's just to support Worker#replayWorkflowExecution functionality
+    // This handler has to be non-sticky to don't evict actual executions from the cache
```
Comment (Sushisource) [inline temporal-sdk/src/main/java/io/temporal/internal/sync/SyncWorkflowWorker.java:101]:
```suggestion
    // Exists to support Worker#replayWorkflowExecution functionality.
    // This handler has to be non-sticky to avoid evicting actual executions from the cache
```

File: temporal-sdk/src/main/java/io/temporal/internal/worker/ReplayerHelper.java [hunk 8]
```diff
@@ -0,0 +1,108 @@
...
+import io.temporal.api.history.v1.HistoryEvent;
+import io.temporal.api.history.v1.WorkflowExecutionStartedEventAttributes;
+import io.temporal.api.query.v1.WorkflowQuery;
+import io.temporal.api.workflowservice.v1.PollWorkflowTaskQueueResponse;
+import io.temporal.api.workflowservice.v1.RespondQueryTaskCompletedRequest;
+import io.temporal.internal.common.WorkflowExecutionHistory;
+import java.util.List;
+import java.util.Optional;
+
+// it's just to support Worker#replayWorkflowExecution functionality
```
Comment (Sushisource) [inline temporal-sdk/src/main/java/io/temporal/internal/worker/ReplayerHelper.java:35]:
```suggestion
// Supports Worker#replayWorkflowExecution functionality
```

File: temporal-sdk/src/main/java/io/temporal/internal/worker/ReplayerHelper.java [hunk 9]
```diff
@@ -0,0 +1,108 @@
...
+
+/**
+ * Incapsulates query implmentation to support {@link
```
Comment (Sushisource) [inline temporal-sdk/src/main/java/io/temporal/internal/worker/ReplayerHelper.java:38]:
```suggestion
 * Encapsulates query implementation to support {@link
```

Comment (Sushisource) [reply temporal-sdk/src/main/java/io/temporal/internal/worker/ReplayerHelper.java:38]: If this is only in support of query functionality I might name it `QueryReplayHelper`

File: temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java (hunk 5 above)
Comment (cretz) [reply temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java:308]: I had this same question: https://github.com/temporalio/sdk-java/pull/881#discussion_r751277467. Apparently this is by intention.

File: temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java (hunk 4 above)
Comment (Spikhalskiy) [reply temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java:271]: While I initially agreed, after a second thought... we still trigger state machines for the workflow task. I would leave the *WorkflowTask name here for this reason.

Comment (Sushisource) [reply temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java:271]: Yeah, I started thinking that after I wrote it. Works for me.

File: temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java (hunk 1 above)
Comment (Spikhalskiy) [reply temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java:139]: Actually no, it doesn't throw, we use the Future non-blocking version of the call.

File: temporal-sdk/src/main/java/io/temporal/internal/replay/QueryResult.java [hunk 10]
```diff
@@ -0,0 +1,41 @@
...
+ */
+
+package io.temporal.internal.replay;
+
+import io.temporal.api.common.v1.Payloads;
+import java.util.Optional;
+
+public class QueryResult {
+  private final Optional<Payloads> responsePayloads;
+  private final boolean finalCommand;
```
Comment (Sushisource) [inline temporal-sdk/src/main/java/io/temporal/internal/replay/QueryResult.java:27]: This should maybe me called `wasFinalCommand` or `finalCommandCreated` here? Because the query itself doesn't really constitute a command.

Perhaps the constructor can have a little doc explaining which situations it'd be set true in.

File: temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java [hunk 11]
```diff
@@ -346,11 +227,114 @@ private Result createCompletedRequest(
...
+
+    return new Result(
+        workflowTask.getWorkflowType().getName(),
+        null,
+        null,
+        queryCompletedRequest.build(),
+        null,
+        false);
+  }
+  /** END OF LEGACY QUERY IMPLEMENTATION */
```
Comment (Sushisource) [inline temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowTaskHandler.java:312]: I think this is unmatched now

File: temporal-sdk/src/main/java/io/temporal/internal/replay/QueryResult.java (hunk 10 above)
Comment (Spikhalskiy) [reply temporal-sdk/src/main/java/io/temporal/internal/replay/QueryResult.java:27]: Makes sense, I will rename and comment. It's true if we queried a finished execution.

**Review by Sushisource — APPROVED** [review]
Looks nice :+1:
