### PR TITLE
Test Server responds NOT_FOUND if the activity is in incorrect state

### LINKED ISSUE #1081: Test flakes with Real Temporal Server leading to infinite activity retry
`io.temporal.internal.testing.WorkflowTestingTest > testActivityFailure`

fails with 

`io.temporal.internal.testing.WorkflowTestingTest > testActivityFailure STANDARD_OUT

    21:11:19.001 [Activity Executor taskQueue="test-workflow", namespace="default": 1] WARN  i.t.i.a.POJOActivityTaskHandler - Activity failure. ActivityId=38334385-1f57-30b4-bc10-97377255f018, activityType=Execute, attempt=1

    java.lang.IllegalThreadStateException: Execute-input1
    	at io.temporal.internal.testing.WorkflowTestingTest$FailingActivityImpl.execute(WorkflowTestingTest.java:596)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at io.temporal.internal.activity.POJOActivityTaskHandler$POJOActivityInboundCallsInterceptor.execute(POJOActivityTaskHandler.java:214)
    	at io.temporal.internal.activity.POJOActivityTaskHandler$POJOActivityImplementation.execute(POJOActivityTaskHandler.java:180)
    	at io.temporal.internal.activity.POJOActivityTaskHandler.handle(POJOActivityTaskHandler.java:120)
    	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:204)
    	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:14)
    	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:93)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    	at java.lang.Thread.run(Thread.java:750)
.......

    21:20:04.797 [Activity Executor taskQueue="test-workflow", namespace="default": 21] WARN  i.t.i.a.POJOActivityTaskHandler - Activity failure. ActivityId=38334385-1f57-30b4-bc10-97377255f018, activityType=Execute, attempt=78094

    java.lang.IllegalThreadStateException: Execute-input1
    	at io.temporal.internal.testing.WorkflowTestingTest$FailingActivityImpl.execute(WorkflowTestingTest.java:596)
    	at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at io.temporal.internal.activity.POJOActivityTaskHandler$POJOActivityInboundCallsInterceptor.execute(POJOActivityTaskHandler.java:214)
    	at io.temporal.internal.activity.POJOActivityTaskHandler$POJOActivityImplementation.execute(POJOActivityTaskHandler.java:180)
    	at io.temporal.internal.activity.POJOActivityTaskHandler.handle(POJOActivityTaskHandler.java:120)
    	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:204)
    	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:164)
    	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:93)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    	at java.lang.Thread.run(Thread.java:750)
```

and getting killed by timeout.

It flakes with real Temporal Server only and may manifest a severe server issue.

[java-sdk-public_build_649_docker-unit-test-with-docker-service.log.zip](https://github.com/temporalio/sdk-java/files/8292866/java-sdk-public_build_649_docker-unit-test-with-docker-service.log.zip)

### PR DESCRIPTION
**Pull request by Spikhalskiy**
Test Server responds NOT_FOUND if the activity is in an incorrect state for a worker trying to finish the activity.
Timeouts are also added to the tests that don't use SDK Test Rule.

Partially addresses #1081

### CODE REVIEW

File: temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java [hunk 1]
```diff
@@ -2476,4 +2481,22 @@ private StateMachine<ChildWorkflowData> getChildWorkflow(long initiatedEventId)
     }
     return child;
   }
+
+  /**
+   * @return true if the activity state is allowing heartbeats and other updates from the activity
+   *     worker
+   */
+  private boolean isActivityInFlightState(StateMachines.State activityState) {
```
Comment (Sushisource) [inline temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java:2489]: Could make this `throwIfActivityNotInFlight` and dedupe the exception throwing by moving it in here

**Review by Sushisource — APPROVED** [review]
