### PR TITLE
Move check for isTemporalDebugModeOn down to WorkflowThreadContext#runUntilBlocked to avoid missing checks on the calling side

### LINKED ISSUE #724: TEMPORAL_DEBUG flag is ignored by deadlock detector in eventLoop
Bug report:
https://community.temporal.io/t/testing-temporal-workflows/2918/4

`SyncWorkflow#eventLoop` lacks a check for `TEMPORAL_DEBUG` flag

### PR DESCRIPTION
**Pull request by Spikhalskiy**
## What was changed
Check for isTemporalDebugModeOn was moved down into `WorkflowThreadContext#runUntilBlocked` so it can't be forgotten by the calling code.

## Why?
We have a missing check for `isTemporalDebugModeOn` in `SyncWorkflow#eventLoop`, so the main event loop doesn't overwrite deadline detection timeout when it should. Instead of fixing this one usage, it's a good idea to move the check to the lower level, so the calling code doesn't have to check the flag explicitly every time.

Closes #724

### CODE REVIEW

File: temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThreadContext.java [hunk 1]
```diff
@@ -216,11 +215,14 @@ public String getYieldReason() {
   }
 
   /**
+   * @param deadlockDetectionTimeoutMs max duration is ms a workflow code can run without yielding
+   *                                   before it's considered deadlocked.
+   *                                   Discarded if Temporal is configured in debug mode.
```
Comment (mfateev) [inline temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThreadContext.java]: I would state the environment variable name in this comment instead of "in debug mode".

File: temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThreadContext.java [hunk 2]
```diff
@@ -216,11 +215,14 @@ public String getYieldReason() {
...
    * @return true if thread made some progress. Which is await was unblocked and some code after it
-   *     was executed.
-   * @param deadlockDetectionTimeout
+   *    *     was executed.
    */
-  public boolean runUntilBlocked(long deadlockDetectionTimeout) {
+  public boolean runUntilBlocked(long deadlockDetectionTimeoutMs) {
+    deadlockDetectionTimeoutMs = getDeadlockDetectionTimeoutMs(deadlockDetectionTimeoutMs);
```
Comment (mfateev) [inline temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThreadContext.java:224]: I would inline this method as it is very short and called from one place only.

**Review by mfateev — COMMENTED** [review]
Would you add a unit test that validates that DEBUG_TIMEOUT actually works?

**Comment by Spikhalskiy** [comment]
@mfateev adapted DeadlockDetectorTest to test both debug and non-debug. But it's a bit ugly, overriding of env variables, especially in static util methods/classes is usually ugly.

**Review by mfateev — APPROVED** [review]
