### PR TITLE
Fixed flaky DetachedScopeTest + Javadoc + Refactoring

### LINKED ISSUE #325: Javadoc for WorkflowClient refers to wrong API
## Expected Behavior

The Javadoc for WorkflowClient class refers to `WorkflowClient.newInstance(temporalServiceHost, temporalServicePort, namespace)` API here - https://github.com/temporalio/sdk-java/blob/2d9ef366807d3fe870e06d98c9eabdf3a93c1207/temporal-sdk/src/main/java/io/temporal/client/WorkflowClient.java#L52 This `newInstance` method signature is not available.

## Actual Behavior

The docs should refer to the correct method.

## Steps to Reproduce the Problem

N/A

## Specifications

 N/A

### PR DESCRIPTION
**Pull request by vkoby**
## What was changed

- Fixed flaky DetachedScopeTest 
- Fixed health check test
- Javadoc from the issue below
- Cleaned up duplicate code in the process
- Utilized SDKWorkflowRule in a few others

1. Closes #325

### CODE REVIEW

File: temporal-sdk/src/test/java/io/temporal/workflow/DetachedScopeTest.java [hunk 1]
```diff
@@ -50,7 +50,7 @@
   public void testDetachedScope() {
     WorkflowStub client = testWorkflowRule.newUntypedWorkflowStubTimeoutOptions("TestWorkflow1");
     client.start(testWorkflowRule.getTaskQueue());
-    testWorkflowRule.sleep(Duration.ofMillis(500)); // To let activityWithDelay start.
+    testWorkflowRule.sleep(Duration.ofSeconds(1)); // To let activityWithDelay start.
```
Comment (vkoby) [inline temporal-sdk/src/test/java/io/temporal/workflow/DetachedScopeTest.java:53]: This should fix the flakiness.

**Review by vitarb — APPROVED** [review]
