### PR TITLE
Fix misc thread safety issues with WorkflowThreadContext

### LINKED ISSUE #641: NPE during performance testing
There was an NPE during performance tests that points to some multithreading issue / race / partial publishing 

```
Caused by: java.lang.NullPointerException: null
at io.temporal.internal.sync.WorkflowThreadContext.runUntilBlocked(WorkflowThreadContext.java:234)
at io.temporal.internal.sync.WorkflowThreadImpl.runUntilBlocked(WorkflowThreadImpl.java:323)
at io.temporal.internal.sync.DeterministicRunnerImpl.runUntilAllBlocked(DeterministicRunnerImpl.java:282)
at io.temporal.internal.sync.SyncWorkflow.eventLoop(SyncWorkflow.java:151)
at io.temporal.internal.replay.ReplayWorkflowExecutor.eventLoop(ReplayWorkflowExecutor.java:74)
at io.temporal.internal.replay.ReplayWorkflowRunTaskHandler$EntityManagerListenerImpl.eventLoop(ReplayWorkflowRunTaskHandler.java:329)
at io.temporal.internal.statemachines.WorkflowStateMachines.eventLoop(WorkflowStateMachines.java:388)
at io.temporal.internal.statemachines.WorkflowStateMachines.lambda$sideEffect$a4cebacf$1(WorkflowStateMachines.java:626)
at io.temporal.internal.statemachines.SideEffectStateMachine.markerResultFromFunc(SideEffectStateMachine.java:164)
at io.temporal.internal.statemachines.FixedTransitionAction.apply(FixedTransitionAction.java:45)
at io.temporal.internal.statemachines.StateMachine.executeTransition(StateMachine.java:137)
... 27 common frames omitted
```

### PR DESCRIPTION
**Pull request by Spikhalskiy**
## What was changed
Fixed unsafe publishing and access to `WorkflowThreadImpl#thread` by refactoring it out and using `WorkflowThreadContext#currentThread`

`WorkflowThreadContext#currentThread` is published and exposed in a thread-safe way

Deadlock detection code checks the thread status after waking up to ensure that it's in a correct state and the state didn't change between the wait timeout and acquiring the lock back.

1. Closes #641

### CODE REVIEW

File: temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThreadContext.java [hunk 1]
```diff
@@ -81,7 +87,7 @@ public void yield(String reason, Supplier<Boolean> unblockFunction) {
         status = Status.YIELDED;
         runCondition.signal();
         yieldCondition.await();
-        mayBeEvaluate(reason);
+        mayBeEvaluateLocked(reason);
```
Comment (Sushisource) [inline temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThreadContext.java:90]: Should probably just be named `maybeEvaluateLocked`

File: temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThreadContext.java [hunk 2]
```diff
@@ -167,6 +175,9 @@ public void setStatus(Status status) {
       this.status = status;
       if (isDone()) {
         runCondition.signal();
+        // it's important to clear the thread after or together (under one lock) with setting the
+        // status, so nobody sees the context yet with RUNNING status, but without a currentThread
```
Comment (Sushisource) [inline temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThreadContext.java:179]:
```suggestion
        // it's important to clear the thread after or together (under one lock) when setting the
        // status, so nobody sees the context yet with RUNNING status, but without a currentThread
```

File: temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThreadContext.java [hunk 3]
```diff
@@ -229,9 +236,25 @@ public boolean runUntilBlocked(long deadlockDetectionTimeout) {
...
       while (status == Status.RUNNING || status == Status.CREATED) {
-        if (!runCondition.await(deadlockDetectionTimeout, TimeUnit.MILLISECONDS)) {
-          throw new PotentialDeadlockException(
-              currentThread.getName(), currentThread.getStackTrace(), this);
+        boolean awaitTimedOut =
+            !runCondition.await(deadlockDetectionTimeout, TimeUnit.MILLISECONDS);
+        if (awaitTimedOut) {
+          // check that the condition is still true after acquiring the lock back (it could be moved
+          // into DONE meanwhile)
+          if (status == Status.RUNNING || status == Status.CREATED) {
```
Comment (Sushisource) [inline temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThreadContext.java:244]: These two topmost `if`s can be combined

**Review by Sushisource — APPROVED** [review]
Awesome. Thanks for digging into this.
