### PR TITLE
Issue 1761 fix supplier reuse

### LINKED ISSUE #1761: Calling WorkflowLocal.set(null) results in the next call to WorkflowLocal.get() to throw a NullPointerException
## Expected Behavior
I expect this:
``` java
public static WorkflowLocal<String> wl = WorkflowLocal.withInitial(() -> "value");
...
wl.get();
wl.set(null);
String s = wl.get();
```
To result in the String `s` being initialized to `null`.

## Actual Behavior
The call to `wl.get()` throws an NullPointerException:
```
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:221) ~[?:?]
	at java.util.Optional.<init>(Optional.java:107) ~[?:?]
	at java.util.Optional.of(Optional.java:120) ~[?:?]
	at io.temporal.internal.sync.DeterministicRunnerImpl.getRunnerLocal(DeterministicRunnerImpl.java:597) ~[temporal-sdk-1.19.1.jar:?]
	at io.temporal.internal.sync.RunnerLocalInternal.get(RunnerLocalInternal.java:30) ~[temporal-sdk-1.19.1.jar:?]
	at io.temporal.workflow.WorkflowLocal.get(WorkflowLocal.java:68) ~[temporal-sdk-1.19.1.jar:?]
        at <line that called wl.get()>
```

Note that this works fine:
``` java
public static WorkflowLocal<String> wl = WorkflowLocal.withInitial(() -> null);
...
wl.get();
```
The problem only occurs once you've called `set(null)`.

## Steps to Reproduce the Problem
See the code snippet above. The root cause of the bug is that `DeterministicRunnerImpl.getRunnerLocal.getRunnerLocal` returns an `Optional<T>`, which will return `Optional.empty()` if `WorkflowLocal.set` has not been called yet, or use `Optional.of` to wrap whatever was passed to `WorkflowLocal.set` in an `Optional`. When `set(null)` is used, the next `get()` results in a call to `Optional.of(null)`, which throws the NPE. I think that the `Optional<T>` return type just doesn't work here, since this method needs to differentiate between two states: `set` has not been called, or `set` has been called, inclusive of `set` being called with `null`, which `Optional` can't handle.

I also noticed that when `get()` is called for the first time, without `set` being called first, the value returned by the `withInitial` callback is not actually stored anywhere. So repeated calls to `get()` result in repeated calls to the `withInitial` callback. This is surprising behavior to me - not sure if it's intended or not.

## Specifications

  - Version: Java SDK 1.19.1.
  - Platform: Linux

### PR DESCRIPTION
**Pull request by bbqbaron**
See https://github.com/temporalio/sdk-java/pull/1777 for background/most thoughts. This is the more ambitious fix that tries to resolve the "not set"/"null" ambiguity.

Closes #1761 

Nested `Optional` didn't feel great, but I preferred it over the other solutions like "an `Optional` that is also nullable".

### CODE REVIEW

**Comment by Quinn-With-Two-Ns** [comment]
Can we add some tests for `WorkflowLocal`? Just to verify the original issue is resolved and we don't break any existing behaviour?

**Comment by bbqbaron** [comment]
Added a test that I think shows the various required behaviors:

* null initial values are fine
* the supplier is called once
* `set` is reflected in a subsequent `get`

**Comment by bbqbaron** [comment]
Learning about the SDK as I go, it looks like maybe `WorkflowThreadLocal` could have the same problem! Want me to throw that into this PR? Not sure what your PR-scoping preferences are.

**Comment by Quinn-With-Two-Ns** [comment]
Yeah I think it will as well, If you don't mind feel free to include a fix in this PR.

File: temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThreadImpl.java [hunk 1]
```diff
@@ -404,13 +404,22 @@ public <T> void setThreadLocal(WorkflowThreadLocalInternal<T> key, T value) {
     threadLocalMap.put(key, value);
   }
 
+  /**
+   * Retrieve data from runner locals. Returns 1. not found (an empty Optional) 2. found but null
```
Comment (bbqbaron) [inline temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThreadImpl.java:408]:
```suggestion
   * Retrieve data from thread locals. Returns 1. not found (an empty Optional) 2. found but null
```

**Comment by bbqbaron** [comment]
Added. It ends up being basically a copypaste, but only two instances of the same behavior aren't an abstraction etc etc.

**Comment by Quinn-With-Two-Ns** [comment]
I believe CI is failing here because your branch does not have tags. I believe you can run `git fetch --tags --all`

**Comment by bbqbaron** [comment]
> I believe CI is failing here because your branch does not have tags. I believe you can run `git fetch --tags --all`

Sorry @Quinn-With-Two-Ns, despite having used git for a while, I'm not sure what to do here. I can fetch tags and push them to my fork, but I'm not sure how that is affecting tests, and I'm not sure how to affect a change on this PR. Does my branch need to contain some new tag or something?

**Comment by Quinn-With-Two-Ns** [comment]
Sorry it is not your fault, most repositories testing don't require git tags to work, but this one does for now. The reason your branch needs to contain tags is the `gradle` files use git to lookup the tags to figure out what current version is. Just pushing tags to your branch should fix the issue

https://github.com/temporalio/sdk-java/blob/18120b164ac5fdbaac894b84353552671b9a0ec9/gradle/versioning.gradle#L5

**Comment by bbqbaron** [comment]
Ah, there we go; tag-pushing doesn't trigger a CI build. Had to push an inconsequential change to source.

**Review by Quinn-With-Two-Ns — APPROVED** [review]
