### PR TITLE
Exception handling when signaling a terminated Workflow

### LINKED ISSUE #576: TestEnv: Failure signalling an *terminated* external workflow execution from another workflow
## Expected Behavior
Should get ApplicationFailure signaling into a terminated workflow, similar to a closed workflow

## Actual Behavior
22:28:25.463 [ForkJoinPool.commonPool-worker-19] ERROR io.temporal.internal.testservice.TestWorkflowMutableStateImpl - Failure signalling an external workflow execution
io.grpc.StatusRuntimeException: FAILED_PRECONDITION: Attempt to add an eBuilder after a completion eBuilder: event_type: EVENT_TYPE_WORKFLOW_EXECUTION_SIGNALED

## Steps to Reproduce the Problem

  1. Workflow Interface

```
import io.temporal.workflow.SignalMethod;
import io.temporal.workflow.WorkflowInterface;
import io.temporal.workflow.WorkflowMethod;

@WorkflowInterface
public interface ExampleWorkflow {

    @WorkflowMethod
    public String execute(String s);

    @SignalMethod
    public void signal(boolean s);
}

```

  2. WorkflowImpl1
```
import java.time.Duration;
import io.temporal.workflow.Workflow;

public class ExampleWorkflowImpl implements ExampleWorkflow{
    private boolean signal = false;

    @Override
    public String execute(String s) {
        Workflow.await(Duration.ofMinutes(5L), () -> signal);
        Workflow.sleep(Duration.ofMinutes(10L));
        return s;
    }

    @Override
    public void signal(boolean signal) {
        this.signal = signal;
    }
}
```

  3. WorkflowImpl2
```
import io.temporal.failure.ApplicationFailure;
import io.temporal.workflow.Workflow;

public class ExampleWorkflow2Impl implements ExampleWorkflow{
    @Override
    public String execute(String s) {
        try {
            ExampleWorkflow correspondingWorkflow = Workflow.newExternalWorkflowStub(ExampleWorkflow.class, "abc123");
            correspondingWorkflow.signal(true);
        } catch (ApplicationFailure e) {

        }
        return s;
    }

    @Override
    public void signal(boolean s) {

    }
}
```

  4. Run first test in test class
```
public class ExampleWorkflowImplTest {
    private TestWorkflowEnvironment testEnv;
    private Worker worker1, worker2;
    private WorkflowClient client;

    @BeforeEach
    public void setUp() {
        testEnv = TestWorkflowEnvironment.newInstance();
        worker1 = testEnv.newWorker("TEST_QUEUE1");
        worker2 = testEnv.newWorker("TEST_QUEUE2");
        worker1.registerWorkflowImplementationTypes(ExampleWorkflowImpl.class);
        worker2.registerWorkflowImplementationTypes(ExampleWorkflow2Impl.class);
        client = testEnv.getWorkflowClient();
        testEnv.start();
    }

    @Test
    public void testTerminateWorkflowSignalError() {
        ExampleWorkflow workflow1 = client.newWorkflowStub(
                ExampleWorkflow.class,
                WorkflowOptions.newBuilder()
                        .setWorkflowId("abc123")
                        .setTaskQueue("TEST_QUEUE1")
                        .build());

        ExampleWorkflow workflow2 = client.newWorkflowStub(
                ExampleWorkflow.class,
                WorkflowOptions.newBuilder()
                        .setTaskQueue("TEST_QUEUE2")
                        .build());

        WorkflowExecution workflow1Execution = WorkflowClient.start(workflow1::execute, "test");

        testEnv.sleep(Duration.ofMinutes(6L));

        WorkflowExecution workflow2Execution = WorkflowClient.start(workflow2::execute, "test");
        WorkflowStub workflowStub1 = WorkflowStub.fromTyped(workflow1);
        workflowStub1.terminate("Mock terminating workflow");

        WorkflowStub workflowStub2 = WorkflowStub.fromTyped(workflow2);
        workflowStub2.getResult(String.class);
    }

    @Test
    public void testSetWorkflowExecutionTimeoutHangs() {
        ExampleWorkflow workflow = client.newWorkflowStub(
                ExampleWorkflow.class,
                WorkflowOptions.newBuilder()
                        // setting this makes the test hang... this normally works outside of TestWorkflowEnv
                        .setWorkflowExecutionTimeout(Duration.ofSeconds(10))
                        .setTaskQueue("TEST_QUEUE1")
                        .build());

        WorkflowExecution workflowExecution = WorkflowClient.start(workflow::execute, "test");

        // workflow execution timeout seems to clash with testEnv.sleep
        testEnv.sleep(Duration.ofMinutes(5L));

        WorkflowStub workflowStub = WorkflowStub.fromTyped(workflow);
        String result = workflowStub.getResult(String.class);
    }

    @Test
    public void testTestEnvSecondTimerSkipped() {
        ExampleWorkflow workflow = client.newWorkflowStub(
                ExampleWorkflow.class,
                WorkflowOptions.newBuilder()
                        .setTaskQueue("TEST_QUEUE1")
                        .build());

        WorkflowExecution workflowExecution = WorkflowClient.start(workflow::execute, "test");

        testEnv.sleep(Duration.ofMinutes(5L));

        WorkflowStub workflowStub = WorkflowStub.fromTyped(workflow);
        String result = workflowStub.getResult(String.class);
        // why is this able to get past 2nd 10min-timer immediately without moving testEnv time further?
        System.out.println(result);
    }
}
```

## Specifications

  - Version: sdk 1.0.0, junit 5
  - Platform: MacOS BigSur

### PR DESCRIPTION
**Pull request by vkoby**
## What was changed
Exception handling when signaling a terminated Workflow

## Why?
If you signal a terminated workflow you get a weird error and the workflow just hangs forever. 

1. Closes #576 

2. How was this tested:
Unit test

### CODE REVIEW

File: temporal-sdk/src/test/java/io/temporal/workflow/shared/TestWorkflows.java [hunk 1]
```diff
@@ -158,6 +158,16 @@
     void mySignal(String value);
   }
 
+  @WorkflowInterface
+  public interface ExampleWorkflow {
```
Comment (Spikhalskiy) [inline temporal-sdk/src/test/java/io/temporal/workflow/shared/TestWorkflows.java:162]: If you created `TestWorkflows` class with an intention of reusing interfaces/implementations from here across tests - the names of the classes should be more descriptive. `ExampleWorkflow` is not a descriptive name, any interface in this class can be named this name. Please rename it to something like `WorkflowWithSignal`.
BTW, there is already an interface `TestSignaledWorkflow` in this class that looks completely appropriate for this use-case, so please consider reusing instead of making a new one.

File: temporal-sdk/src/test/java/io/temporal/workflow/signalTests/SignalTerminatedWorkflowTest.java [hunk 2]
```diff
@@ -0,0 +1,98 @@
...
+
+  @Rule
+  public SDKTestWorkflowRule testWorkflowRule =
+      SDKTestWorkflowRule.newBuilder()
+          .setWorkflowTypes(WorkflowImpl.class, SignalingWorkflowImpl.class)
+          .build();
+
+  @Test
+  public void testTerminateWorkflowSignalError() {
+    System.out.println("Client starting workflow 1:");
```
Comment (Spikhalskiy) [inline temporal-sdk/src/test/java/io/temporal/workflow/signalTests/SignalTerminatedWorkflowTest.java:46]: Please remove this line, it will just pollute logs.

File: temporal-sdk/src/test/java/io/temporal/workflow/signalTests/SignalTerminatedWorkflowTest.java [hunk 3]
```diff
@@ -0,0 +1,98 @@
...
+    WorkflowOptions options =
+        WorkflowOptions.newBuilder()
+            .setTaskQueue(testWorkflowRule.getTaskQueue())
+            .setWorkflowId("abc123")
```
Comment (Spikhalskiy) [inline temporal-sdk/src/test/java/io/temporal/workflow/signalTests/SignalTerminatedWorkflowTest.java:50]: please move the id to a constant with a descriptive name, it will help the readability of this test a lot.

File: temporal-sdk/src/test/java/io/temporal/workflow/signalTests/SignalTerminatedWorkflowTest.java [hunk 4]
```diff
@@ -0,0 +1,98 @@
...
+            .build();
+    ExampleWorkflow workflow =
+        testWorkflowRule.getWorkflowClient().newWorkflowStub(ExampleWorkflow.class, options);
+    WorkflowClient.start(workflow::execute, testWorkflowRule.getTaskQueue());
+
+    testWorkflowRule.sleep(Duration.ofSeconds(7));
```
Comment (Spikhalskiy) [inline temporal-sdk/src/test/java/io/temporal/workflow/signalTests/SignalTerminatedWorkflowTest.java:56]: I'm not familiar enough with JavaSDK time skipping, but is it possible to use larger time periods + time-skipping functionality? Writing tests that rely on single seconds sleeps is always a direct way to flaky tests down the road.

File: temporal-testing/src/main/java/io/temporal/internal/testservice/TestWorkflowStoreImpl.java [hunk 5]
```diff
@@ -92,19 +93,17 @@ void addAllLocked(List<HistoryEvent> events, Timestamp eventTime) {
...
+          throw ApplicationFailure.newNonRetryableFailure("Workflow execution completed.", "");
         }
         eBuilder.setEventId(history.size() + 1L);
         // It can be set in StateMachines.startActivityTask
         if (Timestamps.toMillis(eBuilder.getEventTime()) == 0) {
           eBuilder.setEventTime(eventTime);
         }
         history.add(eBuilder.build());
-        completed = completed || WorkflowExecutionUtils.isWorkflowExecutionCompletedEvent(eBuilder);
+        if (WorkflowExecutionUtils.isWorkflowExecutionCompletedEvent(eBuilder)) {
```
Comment (Spikhalskiy) [inline temporal-testing/src/main/java/io/temporal/internal/testservice/TestWorkflowStoreImpl.java:104]: why do we need this change? The code to the left is more canonical and easy to read.

File: temporal-testing/src/main/java/io/temporal/internal/testservice/StateMachines.java [hunk 6]
```diff
@@ -1517,50 +1517,31 @@ private static State failActivityTask(
...
   }
 
   private static State failActivityTaskById(
       RequestContext ctx, ActivityTaskData data, RespondActivityTaskFailedByIdRequest request) {
-    if (!request.getFailure().hasApplicationFailureInfo()) {
-      throw new IllegalArgumentException("application failure expected: " + request.getFailure());
+    return getState(ctx, data, request.getFailure(), request.getIdentity());
+  }
+
+  private static State getState(
```
Comment (Spikhalskiy) [inline temporal-testing/src/main/java/io/temporal/internal/testservice/StateMachines.java:1528]: This method is structured incorrectly.
It's not a getter (getters don't mutate their arguments and ideally don't have arguments) and the name getState doesn't represent its function (the main function here is creation and publishing of HistoryEvent).

Instead of separating `getState` method this way, here it's better to:
1. Remove one of duplicates. `failActivityTaskByTaskToken` or `failActivityTaskById`. Rename the left one into `failActivityTask`
2. If you want to improve readability of this method, you could separate this piece:
```
    data.startedEventId = ctx.addEvent(data.startedEvent);
     ActivityTaskFailedEventAttributes.Builder a =
         ActivityTaskFailedEventAttributes.newBuilder()
             .setIdentity(request.getIdentity())
             .setScheduledEventId(data.scheduledEventId)
             .setFailure(request.getFailure())
             .setRetryState(retryState)
             .setIdentity(request.getIdentity())
             .setStartedEventId(data.startedEventId);
     HistoryEvent event =
         HistoryEvent.newBuilder()
             .setEventType(EventType.EVENT_TYPE_ACTIVITY_TASK_FAILED)
             .setActivityTaskFailedEventAttributes(a)
             .build();
     ctx.addEvent(event);
```
into a separate method with a meaningful name.

File: temporal-sdk/src/test/java/io/temporal/workflow/signalTests/SignalTerminatedWorkflowTest.java [hunk 7]
```diff
@@ -0,0 +1,98 @@
...
+
+  public static class SignalingWorkflowImpl implements TestWorkflowReturnString {
+    @Override
+    public String execute() {
+      try {
+        ExampleWorkflow correspondingWorkflow =
+            Workflow.newExternalWorkflowStub(ExampleWorkflow.class, "abc123");
+        correspondingWorkflow.signal(true);
+      } catch (ApplicationFailure e) {
+        // ignore
```
Comment (Spikhalskiy) [inline temporal-sdk/src/test/java/io/temporal/workflow/signalTests/SignalTerminatedWorkflowTest.java:93]: Is it a good idea instead of ignoring to actually make explicit checks? I believe we want to actually check as a part of the unit test that the exception has been thrown and probably check a message/type.

File: temporal-testing/src/main/java/io/temporal/internal/testservice/TestWorkflowStoreImpl.java (hunk 5 above)
Comment (vkoby) [reply temporal-testing/src/main/java/io/temporal/internal/testservice/TestWorkflowStoreImpl.java:104]: Hm, I actually changed it because to me this version is more readable and straight forward. It very clearly states the only condition when completed becomes true. :)

File: temporal-sdk/src/test/java/io/temporal/workflow/signalTests/SignalTerminatedWorkflowTest.java [hunk 8]
```diff
@@ -0,0 +1,108 @@
...
+    WorkflowStub workflowStub2 = WorkflowStub.fromTyped(signalingWorkflow);
+    assertEquals(workflowStub2.getResult(String.class), "Success!");
+  }
+
+  public static class WorkflowImpl implements TestSignaledWorkflow {
+    private String signal;
+
+    @Override
+    public String execute() {
+      Workflow.await(Duration.ofSeconds(1), () -> signal == TEST_SIGNAL);
```
Comment (Spikhalskiy) [inline temporal-sdk/src/test/java/io/temporal/workflow/signalTests/SignalTerminatedWorkflowTest.java:80]: String comparison should be done using .equals
Also, it looks like this workflow is finishing successfully right now, it's likely not getting terminated.
We probably want to fix this one to actually hang. Probably by doing 
```
latch.countDown();
Workflow.await(Duration.ofDays(100500), () -> signal == TEST_SIGNAL);
```
We also want to add a workflow that successfully finishes just to test that both scenario work correctly and with the same outcome.

File: temporal-sdk/src/test/java/io/temporal/workflow/signalTests/SignalTerminatedWorkflowTest.java [hunk 9]
```diff
@@ -0,0 +1,108 @@
...
+  }
+
+  public static class SignalingWorkflowImpl implements TestWorkflowReturnString {
+    @Override
+    public String execute() {
+      try {
+        TestSignaledWorkflow stub =
+            Workflow.newExternalWorkflowStub(TestSignaledWorkflow.class, WORKFLOW_ID);
+        stub.signal(TEST_SIGNAL);
+        fail();
```
Comment (Spikhalskiy) [inline temporal-sdk/src/test/java/io/temporal/workflow/signalTests/SignalTerminatedWorkflowTest.java:98]: please add a comment to this fail like fail("exception is expected")

**Review by Spikhalskiy — APPROVED** [review]
