### PR TITLE
Fail WFT if Local Activity execution experienced an Error

### LINKED ISSUE #1533: Error in a local activity should fail the WorkflowTask instead of failing an activity execution
# Current behavior

Currently, Local Activities lack graceful support for Errors that may happen in the Activity thread. If this happens we fail the local activity execution with `RetryState.RETRY_STATE_INTERNAL_SERVER_ERROR`. 

# Expected behavior

If Local Activity throws an `Error`, it should immediately fail Workflow Task. Java Error signals a problem with the Worker and shouldn't lead to a failure of a Local Activity execution or a Workflow.

### PR DESCRIPTION
**Pull request by Spikhalskiy**
## What was changed
Now if a Local Activity throws an `Error`, it will lead to WFT failure, not a failure of activity execution.

Closes #1533

### CODE REVIEW

File: temporal-sdk/src/main/java/io/temporal/internal/replay/WorkflowRunTaskHandler.java [hunk 1]
```diff
@@ -35,10 +35,11 @@ public interface WorkflowRunTaskHandler {
    *
    * @param workflowTask task to handle
    * @return an object that can be used to build workflow task completion or failure response
+   * @throws Throwable if processing experienced unrecoverable unexpected issues
```
Comment (Sushisource) [inline temporal-sdk/src/main/java/io/temporal/internal/replay/WorkflowRunTaskHandler.java:38]: Should this say "unrecoverable"? Since the idea is to let it try again with WFT failure? Unrecoverable for some smaller scope, but recoverable in the bigger sense.

**Review by Sushisource — APPROVED** [review]
Makes sense to me -- this behavior should probably be added to the docstring for `newLocalActivityStub` / wherever else you can start LAs from `Workflow`

File: temporal-sdk/src/main/java/io/temporal/internal/replay/WorkflowRunTaskHandler.java (hunk 1 above)
Comment (Spikhalskiy) [reply temporal-sdk/src/main/java/io/temporal/internal/replay/WorkflowRunTaskHandler.java:38]: Yeah, it may be unclear with this wording. I actually mean "Unrecoverable on this worker in the context of this Workflow Task". Because you are totally correct, it doesn't mean that it's unrecoverable for the workflow, hence WFT failure. I will add a clarification.

**Comment by Spikhalskiy** [comment]
@Sushisource Java devs never throw Errors, so I feel it's overcommunication and just an implied correct behavior. But it may be worth mentioning in LA section of our Developer Guide for Java.

**Comment by bergundy** [comment]
I think I'm missing context here, why is this the intended behavior?

**Comment by Spikhalskiy** [comment]
@bergundy it's explained in the original issue and in the test comment:

```
 * If Local Activity throws an {@link Error}, it should immediately fail Workflow Task. Java Error
 * signals a problem with the Worker and shouldn't lead to a failure of a Local Activity execution
 * or a Workflow.
```

Users wouldn't expect a failure of a Workflow just because their worker is OutOfMemory. Now it leads to a final Local Activity failure.

**Comment by Spikhalskiy** [comment]
@bergundy 
There is no IOError, there is IOException.
There are no exceptions here pretty much, any Error happening in Local Activity is an unrecoverable failure of the JVM by definition of Error.

**Comment by bergundy** [comment]
Looks like there is an `IOError` class that is thrown in extreme cases https://docs.oracle.com/javase/7/docs/api/java/io/IOError.html

According to [Stackoverflow](https://stackoverflow.com/questions/29202584/when-might-an-ioerror-be-thrown), it usually would be thrown from `Console` methods and it's much more typical to get an `IOException`.

Is `AssertionError` supposed to fail the workflow task? I'm not certain.

Anyways, I'm not sure why we need this special behavior for `Error`s but it seems like it should be relatively harmless to merge.

**Comment by Spikhalskiy** [comment]
@bergundy Yeah, I forgot about this guy. IOError is thrown if the file system is broken or some interface is completely inaccessible. For example, your app is reading from console, but the app has no more STDIN (you will get it with Ctrl + D I believe). Anyway, an Error means that the app can't do its job anymore. If a Worker can't do its job, it should never be able to fail an Execution.

**Comment by bergundy** [comment]
Might as well throw a critical failure from the worker in this case instead of failing a WFT.
This behavior might affect low latency applications negatively preventing workflows from completing in a timely fashion.

**Comment by Spikhalskiy** [comment]
@bergundy Nah, there may be some problems with Control code logic that is specific for this specific workflow. We don't want such a workflow to kill the whole workers fleet. WFT failure is the right reaction on such a "Bug" or an "Unexpected state".

**Comment by Spikhalskiy** [comment]
@bergundy Yes, this may be added, while it's tricky. Most java frameworks don't do it. The problem is that there is no reliable way to do anything after an Error, including shutting down a worker. There is also no easy standard way to notify user's code about it. 
But we still should at least try to explicitly fail WFT, and actually specifically for low-latency applications usecase. Otherwise, the Server will have to wait until WFT timeout.

**Comment by bergundy** [comment]
I agree not waiting for WFT timeout is better here but the server also throttles WFT retries with backoff so failing local activity and reporting to the workflow ASAP is the better outcome in (what I believe is) most latency sensitive cases.

**Comment by Spikhalskiy** [comment]
@bergundy 
1.I don't think that even for most even latency sensitive usecases a failure is better than a delay. In some - sure, but not for the majority. 
2. After an Error, reliable reporting of Workflow failure is not possible by Error spec in Java. By this PR I made sure Error will always lead to either a timeout or an explicit WFT failure.
3. To correctly address your situation a low latency app that is absolutely not ready to wait should set scheduleToClose on the workflow. If case of Error, activity didn't really fail. It is the worker who failed.

Unrelated, In addition, for low latency mode of operation we will probably have to reconsider WFT backoff. WFT failure in low latency mode should cause immediate scheduling.

**Comment by bergundy** [comment]
Let's discuss off PR.
