### PR TITLE
Use ReplayAwareScope to don't double report completion on replays, fix STICKY_CACHE_THREAD_FORCED_EVICTION double reporting

### LINKED ISSUE #201: STICKY_CACHE_THREAD_FORCED_EVICTION double reporting
## Actual Behavior

`WorkflowThreadImpl#start` in case of full thread pool triggers `getWorkflowContext().getMetricsScope().counter(MetricsType.STICKY_CACHE_THREAD_FORCED_EVICTION).inc(1)` directly from it's code, after that it calls `cache.evictAnyNotInProcessing` which triggers the metrics increment one more time inside:
`metricsScope.counter(MetricsType.STICKY_CACHE_THREAD_FORCED_EVICTION).inc(1)`

## Proposed solution

Remove unconditional increment from `WorkflowThreadImpl#start` and leave more correct and checked increment inside `cache.evictAnyNotInProcessing`

### LINKED ISSUE #759: Querying a completed workflow increments "temporal_workflow_completed_total" metrics counter
My impression is that this metric should reflect the number of workflows completed for a specific combination of `namespace`, `task_queue` and `workflow_type` tags. If this assumption is incorrect, please describe what this metric reflects and disregard this report.

## Expected Behavior
Querying a completed workflow should not affect the `temporal_workflow_completed_total` metric counter for a `workflow_type`.

## Actual Behavior
Querying a completed workflow increments the `temporal_workflow_completed_total` for the relevant `workflow_type` by 1 per Query request.

## Steps to Reproduce the Problem
Worker setup:
```java
MicrometerClientStatsReporter reporter = new MicrometerClientStatsReporter(
        new PrometheusMeterRegistry(
                PrometheusConfig.DEFAULT,
                CollectorRegistry.defaultRegistry,
                Clock.SYSTEM
        )
);

Scope metricScope = new RootScopeBuilder()
        .reporter(reporter)
        .reportEvery(Duration.ofSeconds(10));

HTTPServer metricsServer = new HTTPServer(9090);

WorkflowServiceStubs service = WorkflowServiceStubs.newInstance(
        WorkflowServiceStubsOptions.newBuilder()
                .setMetricsScope(metricScope)
                .build()
);
```
1. Start a workflow, let it complete.
2. Verify that the `temporal_workflow_completed_total` metric counter for that workflow is now 1.
3. Perform one or more queries for the completed workflow (via tctl / sdk).
4. The `temporal_workflow_completed_total` metric should now have increased beyond 1, without any new workflows completed.

## Specifications

  - micrometer-registry-prometheus version: 1.6.4
  - Prometheus simpleclient version: 0.12.0
  - SDK Version: 1.3.1
  - Platform: macOS / Java 15

### PR DESCRIPTION
**Pull request by Spikhalskiy**
## What was changed
Use ReplayAwareScope for metric reporting to address #759
Remove duplicate STICKY_CACHE_THREAD_FORCED_EVICTION reporting to address #201

Closes #759 
Closes #201

### CODE REVIEW

File: temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThreadImpl.java [hunk 1]
```diff
@@ -249,12 +249,8 @@ public void start() {
         taskFuture = threadPool.submit(task);
         return;
       } catch (RejectedExecutionException e) {
-        getWorkflowContext()
```
Comment (Spikhalskiy) [inline temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowThreadImpl.java:252]: This reporting will be done inside `cache.evictAnyNotInProcessing` call down the line.

**Review by Sushisource — APPROVED** [review]
