### PR TITLE
Fixed an issue with time skipping in case of timing out a root (not a child) workflow

### LINKED ISSUE #577: TestEnv: using workflowExecutionTimeout with testEnv.sleep() makes the test hang
## Expected Behavior
Should be able to set workflowExecutionTimeout on the workflow options as is the case outside of test environment 

## Actual Behavior
Test hangs

## Steps to Reproduce the Problem

  1. WorkflowInterface

```
import io.temporal.workflow.SignalMethod;
import io.temporal.workflow.WorkflowInterface;
import io.temporal.workflow.WorkflowMethod;

@WorkflowInterface
public interface ExampleWorkflow {

    @WorkflowMethod
    public String execute(String s);

    @SignalMethod
    public void signal(boolean s);
}

```
  2. WorkflowImpl1
 
```
import java.time.Duration;
import io.temporal.workflow.Workflow;

public class ExampleWorkflowImpl implements ExampleWorkflow{
    private boolean signal = false;

    @Override
    public String execute(String s) {
        Workflow.await(Duration.ofMinutes(5L), () -> signal);
        Workflow.sleep(Duration.ofMinutes(10L));
        return s;
    }

    @Override
    public void signal(boolean signal) {
        this.signal = signal;
    }
}
```
  3. Run second test in test class
 
```
public class ExampleWorkflowImplTest {
    private TestWorkflowEnvironment testEnv;
    private Worker worker1, worker2;
    private WorkflowClient client;

    @BeforeEach
    public void setUp() {
        testEnv = TestWorkflowEnvironment.newInstance();
        worker1 = testEnv.newWorker("TEST_QUEUE1");
        worker2 = testEnv.newWorker("TEST_QUEUE2");
        worker1.registerWorkflowImplementationTypes(ExampleWorkflowImpl.class);
        worker2.registerWorkflowImplementationTypes(ExampleWorkflow2Impl.class);
        client = testEnv.getWorkflowClient();
        testEnv.start();
    }

    @Test
    public void testTerminateWorkflowSignalError() {
        ExampleWorkflow workflow1 = client.newWorkflowStub(
                ExampleWorkflow.class,
                WorkflowOptions.newBuilder()
                        .setWorkflowId("abc123")
                        .setTaskQueue("TEST_QUEUE1")
                        .build());

        ExampleWorkflow workflow2 = client.newWorkflowStub(
                ExampleWorkflow.class,
                WorkflowOptions.newBuilder()
                        .setTaskQueue("TEST_QUEUE2")
                        .build());

        WorkflowExecution workflow1Execution = WorkflowClient.start(workflow1::execute, "test");

        testEnv.sleep(Duration.ofMinutes(6L));

        WorkflowExecution workflow2Execution = WorkflowClient.start(workflow2::execute, "test");
        WorkflowStub workflowStub1 = WorkflowStub.fromTyped(workflow1);
        workflowStub1.terminate("Mock terminating workflow");

        WorkflowStub workflowStub2 = WorkflowStub.fromTyped(workflow2);
        workflowStub2.getResult(String.class);
    }

    @Test
    public void testSetWorkflowExecutionTimeoutHangs() {
        ExampleWorkflow workflow = client.newWorkflowStub(
                ExampleWorkflow.class,
                WorkflowOptions.newBuilder()
                        // setting this makes the test hang... this normally works outside of TestWorkflowEnv
                        .setWorkflowExecutionTimeout(Duration.ofSeconds(10))
                        .setTaskQueue("TEST_QUEUE1")
                        .build());

        WorkflowExecution workflowExecution = WorkflowClient.start(workflow::execute, "test");

        // workflow execution timeout seems to clash with testEnv.sleep
        testEnv.sleep(Duration.ofMinutes(5L));

        WorkflowStub workflowStub = WorkflowStub.fromTyped(workflow);
        String result = workflowStub.getResult(String.class);
    }

    @Test
    public void testTestEnvSecondTimerSkipped() {
        ExampleWorkflow workflow = client.newWorkflowStub(
                ExampleWorkflow.class,
                WorkflowOptions.newBuilder()
                        .setTaskQueue("TEST_QUEUE1")
                        .build());

        WorkflowExecution workflowExecution = WorkflowClient.start(workflow::execute, "test");

        testEnv.sleep(Duration.ofMinutes(5L));

        WorkflowStub workflowStub = WorkflowStub.fromTyped(workflow);
        String result = workflowStub.getResult(String.class);
        // why is this able to get past 2nd 10min-timer immediately without moving testEnv time further?
        System.out.println(result);
    }
}

```
## Specifications

  - Version: sdk 1.0.0, junit 5
  - Platform: MacOS BigSur

### PR DESCRIPTION
**Pull request by Spikhalskiy**
## What was changed
Fixed an issue with time-skipping during timing out of a not-a-child workflow without a parent.
Also includes some refactorings to use `LockHandle` more extensively to clean up the internal state of `SelfAdvancingTimerImpl`. This makes debugging of time skipping issues easier.

## Why?
#577

## Checklist

1. Closes #577

2. How was this tested:
`TestWorkflowEnvironmentSleepTest#testWorkflowTimeoutDuringSleep`

### CODE REVIEW

File: temporal-testing/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java [hunk 1]
```diff
@@ -1810,7 +1810,7 @@ private void timeoutWorkflow() {
             // TODO(maxim): real retry status
             workflow.action(StateMachines.Action.TIME_OUT, ctx, RetryState.RETRY_STATE_TIMEOUT, 0);
             workflowTaskStateMachine.getData().workflowCompleted = true;
-            if (parent != null) {
+            if (parent.isPresent()) {
```
Comment (Spikhalskiy) [inline temporal-testing/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java:1813]: This is the main fix

File: temporal-testing/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java [hunk 2]
```diff
@@ -1637,11 +1637,12 @@ private void addActivityRetryTimer(RequestContext ctx, StateMachine<ActivityTask
           if (activity.getState() != State.INITIATED && data.getAttempt() != attempt) {
             return;
           }
-          selfAdvancingTimer.lockTimeSkipping(
+          LockHandle lockHandle = selfAdvancingTimer.lockTimeSkipping(
               "activityRetryTimer " + activity.getData().scheduledEvent.getActivityId());
           boolean unlockTimer = false;
           try {
             update(ctx1 -> ctx1.addActivityTask(data.activityTask));
+            //shouldn't we unlock timer here too to avoid the leak?
```
Comment (Spikhalskiy) [inline temporal-testing/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java:1645]: @mfateev ?

File: temporal-testing/src/test/java/io/temporal/testing/TestWorkflowEnvironmentSleepTest.java [hunk 3]
```diff
@@ -51,16 +57,17 @@ protected void failed(Throwable e, Description description) {
   @WorkflowInterface
   public interface ExampleWorkflow {
     @WorkflowMethod
-    void execute();
+    String execute();
```
Comment (vkoby) [inline temporal-testing/src/test/java/io/temporal/testing/TestWorkflowEnvironmentSleepTest.java:60]: I think you can use TestWorkflows.TestSignaledWorkflow here.

File: temporal-testing/src/test/java/io/temporal/testing/TestWorkflowEnvironmentSleepTest.java [hunk 4]
```diff
@@ -79,22 +85,48 @@ public void setUp() {
...
     client = testEnv.getWorkflowClient();
     worker.registerWorkflowImplementationTypes(ExampleWorkflowImpl.class);
-    workflow =
-        client.newWorkflowStub(
-            ExampleWorkflow.class,
-            WorkflowOptions.newBuilder().setTaskQueue(WORKFLOW_TASK_QUEUE).build());
     testEnv.start();
   }
 
+  @After
```
Comment (vkoby) [inline temporal-testing/src/test/java/io/temporal/testing/TestWorkflowEnvironmentSleepTest.java:91]: You can refactor this to use SDKTestWorkflowRule, then setting up clients, workers @Before & @After by hand are not needed.

File: temporal-testing/src/main/java/io/temporal/internal/testservice/SelfAdvancingTimerImpl.java [hunk 5]
```diff
@@ -23,10 +23,7 @@
 import io.temporal.workflow.Functions;
 import java.sql.Timestamp;
 import java.time.Duration;
-import java.util.Comparator;
-import java.util.LinkedList;
-import java.util.List;
-import java.util.PriorityQueue;
+import java.util.*;
```
Comment (vkoby) [inline temporal-testing/src/main/java/io/temporal/internal/testservice/SelfAdvancingTimerImpl.java:26]: Nit: Please use single class imports.

File: temporal-testing/src/test/java/io/temporal/testing/TestWorkflowEnvironmentSleepTest.java [hunk 6]
```diff
@@ -51,16 +57,17 @@ protected void failed(Throwable e, Description description) {
...
     @SignalMethod
     void signal();
   }
 
   public static class ExampleWorkflowImpl implements ExampleWorkflow {
     @Override
-    public void execute() {
+    public String execute() {
       Workflow.sleep(Duration.ofMinutes(20));
+      return "test";
```
Comment (vkoby) [inline temporal-testing/src/test/java/io/temporal/testing/TestWorkflowEnvironmentSleepTest.java:70]: I don't see you use this string anywhere, why return it?

File: temporal-testing/src/test/java/io/temporal/testing/TestWorkflowEnvironmentSleepTest.java (hunk 3 above)
Comment (vkoby) [reply temporal-testing/src/test/java/io/temporal/testing/TestWorkflowEnvironmentSleepTest.java:60]: Nvm, it's in a different package. Maybe just change the name to something more descriptive.

File: temporal-testing/src/main/java/io/temporal/internal/testservice/SelfAdvancingTimerImpl.java (hunk 5 above)
Comment (Spikhalskiy) [reply temporal-testing/src/main/java/io/temporal/internal/testservice/SelfAdvancingTimerImpl.java:26]: We dropped this rule, let's go with Idea defaults about imports.

File: temporal-testing/src/main/java/io/temporal/internal/testservice/SelfAdvancingTimerImpl.java [hunk 7]
```diff
@@ -97,7 +94,13 @@ private void runLocked() {
       while (!Thread.currentThread().isInterrupted()) {
         updateTimeLocked();
         if (!emptyQueue && tasks.isEmpty()) {
-          lockTimeSkippingLocked("runLocked"); // Switching to wall time when no tasks scheduled
+          if (timeLockOnEmptyQueueHandle != null) {
+            throw new IllegalStateException(
+                "SelfAdvancingTimerImpl should have a taken time lock when queue is not empty, but handle is not null");
```
Comment (Sushisource) [inline temporal-testing/src/main/java/io/temporal/internal/testservice/SelfAdvancingTimerImpl.java:99]: Message is confusing here. Is it supposed to say "should *not* have taken" ?

File: temporal-testing/src/main/java/io/temporal/internal/testservice/SelfAdvancingTimerImpl.java [hunk 8]
```diff
@@ -181,6 +184,11 @@ public TimerLockHandle(LockEvent event) {
 
     @Override
     public void unlock() {
+      unlock(null);
+    }
+
+    @Override
+    public void unlock(String caller) {
```
Comment (Sushisource) [inline temporal-testing/src/main/java/io/temporal/internal/testservice/SelfAdvancingTimerImpl.java:191]: `caller` is never used? Is it just so it's more obvious during debugging?

File: temporal-testing/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java [hunk 9]
```diff
@@ -1637,11 +1637,13 @@ private void addActivityRetryTimer(RequestContext ctx, StateMachine<ActivityTask
...
           }
-          selfAdvancingTimer.lockTimeSkipping(
-              "activityRetryTimer " + activity.getData().scheduledEvent.getActivityId());
+          LockHandle lockHandle =
+              selfAdvancingTimer.lockTimeSkipping(
+                  "activityRetryTimer " + activity.getData().scheduledEvent.getActivityId());
           boolean unlockTimer = false;
           try {
             update(ctx1 -> ctx1.addActivityTask(data.activityTask));
+            // shouldn't we unlock timer here too to avoid the leak?
```
Comment (Sushisource) [inline temporal-testing/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java:1646]: Sure seems like it, otherwise that lock is dropped forever. Can't imagine why that would be a good thing.

Comment (Sushisource) [reply temporal-testing/src/main/java/io/temporal/internal/testservice/TestWorkflowMutableStateImpl.java:1646]: Unless this callback is invoked repeatedly

File: temporal-testing/src/test/java/io/temporal/testing/TestWorkflowEnvironmentSleepTest.java [hunk 10]
```diff
@@ -57,7 +63,7 @@ protected void failed(Throwable e, Description description) {
     void signal();
   }
 
-  public static class ExampleWorkflowImpl implements ExampleWorkflow {
+  public static class HingingWorkflowWithSignalImpl implements ExampleWorkflow {
```
Comment (Sushisource) [inline temporal-testing/src/test/java/io/temporal/testing/TestWorkflowEnvironmentSleepTest.java:66]: Hinging? Hanging?

**Review by Sushisource — APPROVED** [review]

File: temporal-testing/src/main/java/io/temporal/internal/testservice/SelfAdvancingTimerImpl.java (hunk 7 above)
Comment (Spikhalskiy) [reply temporal-testing/src/main/java/io/temporal/internal/testservice/SelfAdvancingTimerImpl.java:99]: Yeah, copy-paste from line 290 with partial editing :) Will fix the message.

File: temporal-testing/src/main/java/io/temporal/internal/testservice/SelfAdvancingTimerImpl.java (hunk 8 above)
Comment (Spikhalskiy) [reply temporal-testing/src/main/java/io/temporal/internal/testservice/SelfAdvancingTimerImpl.java:191]: Yeah. We remove the handle and there is no place to put the message, but I want to kinda promote using this version of the method, so at least you can add a debug printing when you need to investigate what's going on with time locks.
